export const recipes = [
  {
    id: 'r1',
    name: 'Ensalada mediterránea',
    description: 'Lechuga, tomate, pepino, garbanzos, aceite de oliva',
    calories: 420,
    protein: 12,
    carbs: 40,
    fats: 22,
    price: 6.5,
    photo_url: '/images/salad.svg',
  },
  {
    id: 'r2',
    name: 'Bowl de pollo y quinoa',
    description: 'Pollo a la plancha, quinoa, verduras asadas, salsa ligera',
    calories: 620,
    protein: 38,
    carbs: 55,
    fats: 18,
    price: 7.9,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r3',
    name: 'Salmón con arroz integral y espárragos',
    description: 'Salmón al horno, arroz integral, espárragos y limón',
    calories: 540,
    protein: 36,
    carbs: 48,
    fats: 18,
    price: 8.9,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r4',
    name: 'Wrap de pavo y aguacate',
    description: 'Tortilla integral, pavo, aguacate, espinacas y tomate',
    calories: 480,
    protein: 32,
    carbs: 42,
    fats: 16,
    price: 6.9,
    photo_url: '/images/salad.svg',
  },
  {
    id: 'r5',
    name: 'Tofu salteado con verduras y arroz jazmín',
    description: 'Tofu marinado, brócoli, zanahoria, pimientos y arroz jazmín',
    calories: 510,
    protein: 25,
    carbs: 60,
    fats: 14,
    price: 7.5,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r6',
    name: 'Poke bowl de atún',
    description: 'Atún fresco, arroz sushi, edamame, aguacate y alga nori',
    calories: 560,
    protein: 34,
    carbs: 52,
    fats: 20,
    price: 9.2,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r7',
    name: 'Pasta integral con pesto y pollo',
    description: 'Pasta integral, pollo a la plancha, pesto casero, parmesano',
    calories: 630,
    protein: 40,
    carbs: 60,
    fats: 20,
    price: 8.3,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r8',
    name: 'Omelette de claras y vegetales',
    description: 'Claras de huevo, espinacas, champiñones, pimientos y tomate',
    calories: 350,
    protein: 28,
    carbs: 14,
    fats: 18,
    price: 5.9,
    photo_url: '/images/salad.svg',
  },
  {
    id: 'r9',
    name: 'Crema de calabaza con semillas',
    description: 'Calabaza asada, cebolla, zanahoria, pipas y aceite de oliva',
    calories: 310,
    protein: 8,
    carbs: 28,
    fats: 16,
    price: 4.9,
    photo_url: '/images/bowl.svg',
  },
  {
    id: 'r10',
    name: 'Bowl vegano de lentejas y batata',
    description: 'Lentejas cocidas, batata asada, kale, tahini y limón',
    calories: 540,
    protein: 22,
    carbs: 65,
    fats: 15,
    price: 7.4,
    photo_url: '/images/bowl.svg',
  }

]

export const availableSlots = [
  { id: 's1', label: '2025-11-03 10:00' },
  { id: 's2', label: '2025-11-04 16:00' },
  { id: 's3', label: '2025-11-06 09:00' },
]
